<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */


//** Force full width content layout
add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );


//** Remove primary navigation
remove_action( 'genesis_before_content_sidebar_wrap', 'genesis_do_nav' );


//** Remove breadcrumbs
remove_action( 'genesis_before_loop', 'genesis_do_breadcrumbs');



//*** Remove homepage loop and content spaces
add_action( 'genesis_before','remove_homepage_content' );
function remove_homepage_content() {
        if (is_front_page() ) { 
        remove_action( 'genesis_loop', 'genesis_do_loop' );
        }
}
add_action( 'genesis_before','remove_homepage_after_content' );
function remove_homepage_after_content() {
        if (is_front_page() ) { 
        add_filter( 'genesis_markup_site-inner', '__return_null' );
        }
}

//*** Footer 
add_action( 'genesis_before','remove_footer_content' );
function remove_footer_content() {
        if (is_front_page() ) { 
        remove_action('genesis_footer', 'genesis_do_footer');
        remove_action('genesis_footer', 'genesis_footer_markup_open', 5);
        remove_action('genesis_footer', 'genesis_footer_markup_close', 15);
        }
}


/* remove_action( 'genesis_loop', 'genesis_do_loop' );*/

/** Add the featured image section */
add_action( 'genesis_after_header', 'full_featured_image' );
function full_featured_image() {
	if ( is_front_page() ) {
		echo '<div id="carouselExampleControls hero-image" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner inner-hero-1 inner-hero-2 inner-hero-3">
    <div class="carousel-item active">
      <img class="d-block w-100 " src="'. get_stylesheet_directory_uri() . '/images/hero2.png" alt="First slide">
    </div>
  </div>
</div>';
	}
	elseif ( is_singular( array( 'post', 'page' ) ) && has_post_thumbnail() ){
		echo '<div id="hero-image">';
		echo get_the_post_thumbnail($thumbnail->ID);
		echo '</div>';
	} 		
} 

add_action( 'genesis_after_header', 'homepage_callout_area' );
function homepage_callout_area() {
if ( is_front_page() ) {

genesis_widget_area ('homepage-callout', array(
        'before' => '',
        'after' => '',
  ) );

  }
}

genesis();




